import type {ScanTarget,Scanner,ScanHistory,CoveragePolicy,CoverageAnalysis,ScanPlan,ScheduledScan,UnscheduledTarget} from "./types.js";
import {sha256,round} from "./canonical.js";
const ISO=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,3})?(?:Z|[+-]\d{2}:\d{2})$/;
function parseIso(value:string,label:string):number{if(typeof value!=="string"||!ISO.test(value))throw new Error(`E_TIME: ${label} must be ISO-8601 with timezone`);const n=Date.parse(value);if(!Number.isFinite(n))throw new Error(`E_TIME: invalid ${label}`);return n;}
function parseNow(now:string):number{return parseIso(now,"now");}
function validatePolicy(policy:CoveragePolicy):void{if(!policy||typeof policy!=="object")throw new Error("E_INPUT: policy required");if(!Number.isFinite(policy.horizonMinutes)||policy.horizonMinutes<=0)throw new Error("E_INPUT: positive finite horizon required");if(!Array.isArray(policy.maxAgeHoursByRisk)||policy.maxAgeHoursByRisk.length===0)throw new Error("E_INPUT: at least one risk-age threshold required");for(const [risk,hours] of policy.maxAgeHoursByRisk){if(!Number.isFinite(risk)||risk<0||risk>100||!Number.isFinite(hours)||hours<=0)throw new Error("E_INPUT: invalid risk-age threshold");}}
function maxAgeHours(risk:number,policy:CoveragePolicy):number{const xs=[...policy.maxAgeHoursByRisk].sort((a,b)=>b[0]-a[0]);for(const [min,hours] of xs)if(risk>=min)return hours;return Infinity;}
function ageHours(t:ScanTarget,nowMs:number):number{if(t.lastScannedAt===null)return Infinity;const ts=parseIso(t.lastScannedAt,`lastScannedAt for ${t.id}`);return Math.max(0,(nowMs-ts)/3_600_000);}
function overdue(t:ScanTarget,nowMs:number,p:CoveragePolicy):number{const age=ageHours(t,nowMs);if(age===Infinity)return 1_000_000;const max=maxAgeHours(t.risk,p);return max===Infinity?0:Math.max(0,age-max);}
function compatible(t:ScanTarget,s:Scanner):boolean{const caps=new Set(s.capabilities);return t.requiredCapabilities.every(c=>caps.has(c));}
function median(xs:number[]):number{if(xs.length===0)return NaN;const y=[...xs].sort((a,b)=>a-b),m=Math.floor(y.length/2);return y.length%2?y[m]!:(y[m-1]!+y[m]!)/2;}
function validateInputs(targets:ScanTarget[],scanners:Scanner[],history:ScanHistory[],policy:CoveragePolicy,nowMs:number):void{validatePolicy(policy);const tids=new Set<string>();for(const t of targets){if(!t?.id?.trim()||tids.has(t.id))throw new Error(`E_INPUT: duplicate/empty target ${t?.id}`);tids.add(t.id);if(!Number.isFinite(t.risk)||t.risk<0||t.risk>100)throw new Error(`E_INPUT: risk ${t.id}`);if(!Number.isFinite(t.estimatedMinutes)||t.estimatedMinutes<=0)throw new Error(`E_INPUT: duration ${t.id}`);if(!Array.isArray(t.requiredCapabilities)||t.requiredCapabilities.some(c=>typeof c!=="string"||!c.trim()))throw new Error(`E_INPUT: capabilities ${t.id}`);if(t.lastScannedAt!==null)ageHours(t,nowMs);}const sids=new Set<string>();for(const s of scanners){if(!s?.id?.trim()||sids.has(s.id))throw new Error(`E_INPUT: duplicate/empty scanner ${s?.id}`);sids.add(s.id);if(!Number.isFinite(s.capacityMinutes)||s.capacityMinutes<0)throw new Error(`E_INPUT: scanner capacity ${s.id}`);if(!Array.isArray(s.capabilities)||s.capabilities.some(c=>typeof c!=="string"||!c.trim()))throw new Error(`E_INPUT: scanner capabilities ${s.id}`);}for(const h of history){if(!h?.targetId?.trim()||!h?.scannerId?.trim()||!Number.isFinite(h.durationMinutes)||h.durationMinutes<=0)throw new Error("E_INPUT: invalid history entry");parseIso(h.completedAt,"history completedAt");}}
export function predictDuration(t:ScanTarget,s:Scanner,h:ScanHistory[]):number{const exact=h.filter(x=>x.targetId===t.id&&x.scannerId===s.id).map(x=>x.durationMinutes).filter(x=>Number.isFinite(x)&&x>0);const byTarget=h.filter(x=>x.targetId===t.id).map(x=>x.durationMinutes).filter(x=>Number.isFinite(x)&&x>0);const v=exact.length?median(exact):byTarget.length?median(byTarget):t.estimatedMinutes;if(!Number.isFinite(v)||v<=0)throw new Error(`E_INPUT: no valid duration for ${t.id}`);return Math.max(1,round(v));}
export function analyzeCoverage(targets:ScanTarget[],policy:CoveragePolicy,now:string):CoverageAnalysis{const n=parseNow(now);validateInputs(targets,[],[],policy,n);let coveredRisk=0,totalRisk=0,blind=0;const od:string[]=[],never:string[]=[];for(const t of targets){totalRisk+=t.risk;const o=overdue(t,n,policy);if(t.lastScannedAt===null)never.push(t.id);if(o>0){od.push(t.id);blind+=t.risk}else coveredRisk+=t.risk;}return{totalTargets:targets.length,overdueTargets:od.sort(),neverScannedTargets:never.sort(),riskWeightedCoverage:round(totalRisk?coveredRisk/totalRisk:1),blindRisk:round(blind)};}
export function createPlan(targets:ScanTarget[],scanners:Scanner[],history:ScanHistory[],policy:CoveragePolicy,now:string):ScanPlan{const nowMs=parseNow(now);validateInputs(targets,scanners,history,policy,nowMs);const analysis=analyzeCoverage(targets,policy,now);const ranked=targets.map(t=>({t,ov:overdue(t,nowMs,policy),priority:round(t.risk*1000+Math.min(overdue(t,nowMs,policy),999999))})).filter(x=>x.ov>0).sort((a,b)=>b.priority-a.priority||a.t.id.localeCompare(b.t.id));const load:Record<string,number>=Object.fromEntries(scanners.map(s=>[s.id,0]));const scheduled:ScheduledScan[]=[],unscheduled:UnscheduledTarget[]=[];let scheduledRisk=0;for(const x of ranked){const candidates=scanners.filter(s=>compatible(x.t,s)).map(s=>({s,d:predictDuration(x.t,s,history),remaining:Math.min(s.capacityMinutes,policy.horizonMinutes)-(load[s.id]??0)}));if(!candidates.length){unscheduled.push({targetId:x.t.id,reason:"NO_COMPATIBLE_SCANNER",priority:x.priority});continue;}const fit=candidates.filter(c=>c.d<=c.remaining).sort((a,b)=>(b.remaining-b.d)-(a.remaining-a.d)||a.d-b.d||a.s.id.localeCompare(b.s.id))[0];if(!fit){unscheduled.push({targetId:x.t.id,reason:"CAPACITY_EXHAUSTED",priority:x.priority});continue;}load[fit.s.id]=round((load[fit.s.id]??0)+fit.d);scheduled.push({targetId:x.t.id,scannerId:fit.s.id,durationMinutes:fit.d,priority:x.priority,overdueHours:x.ov});scheduledRisk+=x.t.risk;}const totalRisk=targets.reduce((a,t)=>a+t.risk,0),coveredBefore=analysis.riskWeightedCoverage,coveredAfter=round(totalRisk?Math.min(1,coveredBefore+scheduledRisk/totalRisk):1);const body={now,scheduled,unscheduled,scannerLoad:load,riskWeightedCoverageBefore:coveredBefore,riskWeightedCoverageAfter:coveredAfter,scheduledRisk:round(scheduledRisk)};return{...body,seal:sha256(body)};}
export function verifyPlanSeal(plan:ScanPlan):boolean{const {seal,...body}=plan;return typeof seal==="string"&&seal===sha256(body);}
export function comparePlan(current:ScanPlan,proposed:ScanPlan){if(!verifyPlanSeal(current)||!verifyPlanSeal(proposed))throw new Error("E_SEAL: scan plan seal mismatch");return{coverageDelta:round(proposed.riskWeightedCoverageAfter-current.riskWeightedCoverageAfter),scheduledRiskDelta:round(proposed.scheduledRisk-current.scheduledRisk),unscheduledDelta:proposed.unscheduled.length-current.unscheduled.length,loadDelta:Object.fromEntries([...new Set([...Object.keys(current.scannerLoad),...Object.keys(proposed.scannerLoad)])].sort().map(id=>[id,round((proposed.scannerLoad[id]??0)-(current.scannerLoad[id]??0))]))};}
